version: "3"
services:
  app:
    image: node:lts-alpine3.11
    container_name: nodejs_expenses
    depends_on:
       - mongodb_1
    restart: always
    volumes:
      - ~/nodejs_expenses:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_CONTAINER_NAME=mongodb_1
      - TOKEN_VALUE=${TOKEN_VALUE}
    ports:
      - "0.0.0.0:3001:3001"
    command: npm run dev

  mongodb_1:
    image: mongo
    container_name: mongodb_1
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
    expose:
      - ${MONGO_PORT}
    volumes:
      - ~/mongodb/mongodb-data:/data/db
      - ~/mongodb/init_db/:/docker-entrypoint-initdb.d/
      - ~/mongodb/mongodb_config/mongod.conf:/etc/mongod.conf
